version: '3'

services:
  ldap:
    image: osixia/openldap:latest
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - /Users/davido/projects/gerrit-ldap-to-sso-saml-migration/resources/openldap/var:/var/lib/ldap:rw
      - /Users/davido/projects/gerrit-ldap-to-sso-saml-migration/resources/openldap/etc:/etc/ldap/slapd.d:rw

  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

